using System.Collections.ObjectModel;
using System.Text;
using System.Text.Json;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SabreToolsStudio.Services;

namespace SabreToolsStudio.ViewModels;

/// <summary>
/// One step in the batch script builder: a command plus its raw argument text
/// </summary>
public partial class BatchStep : ObservableObject
{
    public BatchStep(ComboOption command)
    {
        _command = command;
    }

    public IReadOnlyList<ComboOption> Commands => OptionCatalog.BatchCommands;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(Line))]
    private ComboOption _command;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(Line))]
    private string _arguments = "";

    /// <summary>The generated script line for this step</summary>
    public string Line =>
        Arguments.Trim().Length > 0 ? $"{Command.Value}({Arguments.Trim()});" : $"{Command.Value}();";
}

/// <summary>
/// Batch Running feature (batch): run script files of sequential DAT operations,
/// with a visual builder for creating those scripts
/// </summary>
public partial class BatchViewModel : FeaturePageViewModel
{
    public BatchViewModel(SettingsService settings, PresetService presets)
        : base(settings, presets)
    {
        Inputs.CollectionChanged += (_, _) => NotifyCommandChanged();
        Steps.CollectionChanged += (_, _) => OnStepsChanged();
    }

    public override string Title => "Batch";
    public override string Description =>
        "Run batch script files of sequential DAT operations. Each listed file runs independently. Use the builder to compose a script, save it, and it is added to the run list automatically.";
    public override string Flag => "batch";
    public override string FeatureKey => "batch";

    /// <summary>Batch script files to run</summary>
    public ObservableCollection<string> Inputs { get; } = [];

    /// <summary>Steps in the script builder</summary>
    public ObservableCollection<BatchStep> Steps { get; } = [];

    public string ScriptPreview
    {
        get
        {
            if (Steps.Count == 0)
                return "";

            var builder = new StringBuilder();
            builder.AppendLine("# Generated by SabreTools Studio");
            foreach (BatchStep step in Steps)
                builder.AppendLine(step.Line);
            return builder.ToString();
        }
    }

    public bool HasSteps => Steps.Count > 0;

    private void OnStepsChanged()
    {
        foreach (BatchStep step in Steps)
        {
            step.PropertyChanged -= OnStepPropertyChanged;
            step.PropertyChanged += OnStepPropertyChanged;
        }

        OnPropertyChanged(nameof(ScriptPreview));
        OnPropertyChanged(nameof(HasSteps));
    }

    private void OnStepPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e) =>
        OnPropertyChanged(nameof(ScriptPreview));

    [RelayCommand]
    private void AddStep() => Steps.Add(new BatchStep(OptionCatalog.BatchCommands[0]));

    [RelayCommand]
    private void RemoveStep(BatchStep step) => Steps.Remove(step);

    [RelayCommand]
    private void MoveStepUp(BatchStep step)
    {
        int index = Steps.IndexOf(step);
        if (index > 0)
            Steps.Move(index, index - 1);
    }

    [RelayCommand]
    private void MoveStepDown(BatchStep step)
    {
        int index = Steps.IndexOf(step);
        if (index >= 0 && index < Steps.Count - 1)
            Steps.Move(index, index + 1);
    }

    /// <summary>Called by the view after the script is saved to disk</summary>
    public void OnScriptSaved(string path)
    {
        if (!Inputs.Contains(path))
            Inputs.Add(path);
    }

    protected override IEnumerable<string> InputPaths => Inputs;

    protected override IEnumerable<string> BuildOptionArguments() => [];

    #region Presets

    private sealed class BatchStepData
    {
        public string Command { get; set; } = "";
        public string Arguments { get; set; } = "";
    }

    private sealed class BatchPreset
    {
        public List<string> Inputs { get; set; } = [];
        public List<BatchStepData> Steps { get; set; } = [];
    }

    protected override object CapturePreset() => new BatchPreset
    {
        Inputs = [.. Inputs],
        Steps = [.. Steps.Select(s => new BatchStepData { Command = s.Command.Value, Arguments = s.Arguments })],
    };

    protected override void ApplyPreset(JsonElement data)
    {
        BatchPreset? preset;
        try
        {
            preset = data.Deserialize<BatchPreset>();
        }
        catch
        {
            return;
        }

        if (preset is null)
            return;

        Inputs.Clear();
        foreach (string input in preset.Inputs.Where(p => !string.IsNullOrWhiteSpace(p)))
            Inputs.Add(input);

        Steps.Clear();
        foreach (BatchStepData stepData in preset.Steps)
        {
            ComboOption command = OptionCatalog.BatchCommands.FirstOrDefault(c => c.Value == stepData.Command)
                ?? OptionCatalog.BatchCommands[0];
            Steps.Add(new BatchStep(command) { Arguments = stepData.Arguments });
        }
    }

    #endregion
}
